title: IEOR 8100
description: Topics in Reinforcement Learning 
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
# inserts github link in top nav bar (recommended)
github_button_location_top_navbar: false
copyright:
footer: 
