title: IEOR 8100 
description: Advanced topics in IEOR (Reinforcement Learning).
show_downloads: false
github_button_location_top_navbar: true
theme: jekyll-theme-slate
google_analytics: 
copyright: 
footer: 



