title: IEOR 8100 (Reinforcement Learning)
description: The material on this website accompanies Columbia IEOR 8100 course on Reinforcement Learning.
show_downloads: false
github_button_location_top_navbar: true
theme: jekyll-theme-slate
google_analytics: 
copyright: 
footer: 



