title: IEOR 8100
description: Topics in Reinforcement Learning
show_downloads: false
google_analytics: true
github_button_location_top_navbar: true
copyright: false
footer: false
theme: jekyll-theme-slate


