title: IEOR 8100 (Reinforcement Learning)
description: The material on this website accompanies the Columbia IEOR class IE0R 8100: Advanced topics in IEOR (Reinforcement Learning).
show_downloads: false
github_button_location_top_navbar: true
theme: jekyll-theme-slate
google_analytics: 
copyright: 
footer: 



